### PR TITLE
task/#9_fix-link-tag-to-methods

### LINKED ISSUE #9: Fix link tag to methods
Currently adding a link tag (`{@link }`) to a method will generate a link with a text that only has the class/interface but not the method name.

This is due to the package `dgeni-packages/typescript`, generate the methods alias without following the alias templates and adding an index to that method; making the service `getLinkInfo` (of package `dgeni-packages/links`), to fail in finding the corresponding document.

We can consider al least 2 options:
- Implement a custom links service
- Change how aliases are generated to match the current link service

### LINKED ISSUE #17: Overloaded Methods not rendering properly
Some overloaded methods are only getting rendered once.

For example, SPARQLER's [SelectClase.select](https://carbonldp.github.io/sparqler/clauses/SelectClause/#select) is only getting rendered once, even though it has 2 signatures.
```
select( ...variables:string[] ):FromClause<T>;
select( variablesFunction:( builder:PatternBuilder ) => (string | Projectable) | (string | Projectable)[] ):FromClause<T>;
```

### PR DESCRIPTION
**Pull request by inakijaneiro**
Resolved #9.
- Overloaded methods are now correctly rendered
- Modified getLinkInfo service in order to support the following link tag syntax

`{@link MyClass.myMethod}`

### CODE REVIEW

File: src/dgeni/services/encodeCodeBlock.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+    str = '<code' + lang + '>' + str + '</code>';
+
+    // If not inline then wrap the code element in a pre element
+    if ( !inline ) {
+      str = '<pre>' + str + '</pre>';
+    }
+
+    return str;
+  };
+};
```
Comment (roddolf) [inline src/dgeni/services/encodeCodeBlock.ts]: This service is not needed since already exists in `dgeni-packages/base`

File: CHANGELOG.md [hunk 2]
```diff
@@ -15,6 +15,21 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 
 ## [Unreleased]
 
+### Fixed
+
+- [#18](https://github.com/CarbonLDP/carbonldp-ts-docs-engine/pull/18) Fix link tag syntax to support both dot and hash notation ( `MyClass#instanceMethod` and `MyClass.staticMethod` )
```
Comment (roddolf) [inline CHANGELOG.md]: Remove spaces between parentheses.

File: CHANGELOG.md [hunk 3]
```diff
@@ -15,6 +15,21 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
...
+
+- [#12](https://github.com/CarbonLDP/carbonldp-ts-docs-engine/issues/12) Fix asset loading when deployed in gh-pages
+
+## [1.0.0] (2019-11-04)
+
 - First release
 
-[Unreleased]: https://github.com/CarbonLDP/sparqler/compare/5886818...HEAD
\ No newline at end of file
+[Unreleased]: https://github.com/CarbonLDP/sparqler/compare/5886818...HEAD
```
Comment (roddolf) [inline CHANGELOG.md]: Change the commit hash to `v1.0.1`
